#!/bin/bash

OS=$(uname)
if [ "$OS" == "Darwin" ]; then
  $(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
else 
  if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
    fi
  fi
fi
