#!/bin/bash

OS=$(uname)
if [ "$OS" == "Darwin" ]; then
  # Bash completion (installed via Homebrew), better to install bash_completion@2 than bash_completion
  . $(brew --prefix)/etc/bash_completion.d/*
else 
  if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
    fi
  fi
fi
