#!/bin/bash
# Inspired by https://github.com/necolas/dotfiles

# bash_aliases

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Lazy form with retaining colour through unbuffer
alias l="unbuffer ls -lopG | awk '{print\$1,\$8}'"
alias ll="unbuffer ls -opG | awk '{print\$1,\$8}'"

# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Git aliases
alias gs="git status"
alias ga="git add"
alias gap="git add -p"
alias gm="git commit"
alias gmm="git commit -m"
alias gre="git pull --rebase"
alias gpu="git push"


# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
