#!/bin/bash
# Based on https://github.com/necolas/dotfiles

# Get script path - one liner approach. Here be dragons!!
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd)"

load_dotfiles() {
    declare -a files=(
        #$HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
        $SCRIPT_PATH/shell/bash_options # Options
        $SCRIPT_PATH/shell/bash_exports # Exports
        $SCRIPT_PATH/shell/bash_aliases # Aliases
        #$SCRIPT_PATH/shell/functions/* # Functions
        #$SCRIPT_PATH/shell/bash_prompt # Custom bash prompt
        #$SCRIPT_PATH/shell/bash_paths # Path modifications
        #$HOME/bash_profile.local # Local and private settings not under version control (e.g. git credentials)
        $SCRIPT_PATH/shell/bash_profile
        $SCRIPT_PATH/shell/bash_completion
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles
