#!/bin/bash
# Based on https://github.com/necolas/dotfiles

load_dotfiles() {
    declare -a files=(
        #$HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
        $HOME/dotfiles/shell/bash_options # Options
        $HOME/dotfiles/shell/bash_exports # Exports
        $HOME/dotfiles/shell/bash_aliases # Aliases
        #$HOME/dotfiles/shell/functions/* # Functions
        #$HOME/dotfiles/shell/bash_prompt # Custom bash prompt
        #$HOME/dotfiles/shell/bash_paths # Path modifications
        $(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
        #$HOME/bash_profile.local # Local and private settings not under version control (e.g. git credentials)
        $HOME/dotfiles/shell/bash_profile
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles
